version: '3.8'

services:

  koha:
    build:
      context: .
    container_name: koha
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    depends_on:
      - koha-db
    environment:
      DB_HOST: koha-db
      DB_ROOT_PASSWORD: koha
      #DOMAIN: .example.com
      KOHA_TRANSLATE_LANGUAGES: "ca-ES"
      #INTRAPORT: 80
      #INTRAPREFIX: library
      #INTRASUFFIX: .admin
      LIBRARY_NAME: koha
      OPACPREFIX: library
      SLEEP: 3
    #entrypoint: tail -F /dev/null
    ports:
      - "80:80"
      - "8080:8080"

  koha-db:
    container_name: koha-db
    environment:
      MYSQL_ROOT_PASSWORD: koha
    # Newer versions not working
    image: mariadb:10.3

  memcached:
    command: memcached -m 64m
    container_name: memcached
    image: memcached
