version: '3.8'

services:

  koha-db:
    container_name: koha-db
    environment:
      MYSQL_ROOT_PASSWORD: koha
    # Newer versions not working
    image: mariadb:10.3

  koha:
    build:
      context: .
    container_name: koha
    cap_add:
        - SYS_NICE
        - DAC_READ_SEARCH
    depends_on:
        - koha-db
    environment:
      LIBRARY_NAME: koha
      SLEEP: 3
      INTRAPORT: 8080
      DB_HOST: koha-db
      DB_ROOT_PASSWORD: koha
      KOHA_TRANSLATE_LANGUAGES: "ca-ES"
    ports:
      - "80:80"
      - "8080:8080"
