version: '3.7'

services:

  koha-db:
    container_name: koha-db
    # https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=23239
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: koha

  koha:
    container_name: koha
    image: kedu/koha-community
    cap_add:
        - SYS_NICE
        - DAC_READ_SEARCH
    depends_on:
        - koha-db
    environment:
      LIBRARY_NAME: koha
      SLEEP: 3
      INTRAPORT: 8080
      DB_HOST: koha-db
      DB_ROOT_PASSWORD: koha
    ports:
      - "80:80"
      - "8080:8080"
